### PR TITLE
upgraded .net core to 3.1 (LTS version)

### PR DESCRIPTION
**Pull request by marik91**
Added support for .NET 5

### CODE REVIEW

**Comment by marik91** [comment]
Basically with launch of .NET 5 need support of it for this nuget in .net 5 projects
Also updated core 3.0 to 3.1 as 3.1 is LTS and 3.0 would not have any updates (If you don't want this, could revert it)

Also question, after successful merge, when we could expect new nuget would be released?

**Comment by OmidID** [comment]
If there is no more update until next week we could prepare a new package

**Comment by marik91** [comment]
> If there is no more update until next week we could prepare a new package

seems there was no new updates, could I request you to build new package, with recent changes?

**Comment by OmidID** [comment]
@marik91 The package is ready https://www.nuget.org/packages/LottieSharp/1.1.3

**Pull request merged**
