### PR TITLE
Updated ReadMe and created nuget package

### PR DESCRIPTION
**Pull request by quicoli**
I've updated the readme page including a logo and some basic usage. Also, published a nugget version of this awesome library :) 
The nugget is pointing to your repository as project url and ownership if set to Ascora GmbH.

### CODE REVIEW

**Comment by Crayjin** [comment]
Sorry for not having the time to review this.

@quicoli First thank you for investing your time. May I ask where that logo is coming from? I want to make sure, that we don't violate any copyrights.

**Comment by quicoli** [comment]
Hi!

I just got a screenshot from https://airbnb.design/lottie and created the
icon.
I believe we are not violating anything :)

**Comment by Crayjin** [comment]
Hi @quicoli,

unfortunately we need to replace that logo as this is a copyright violation imho. So we have multiple options right now:
- You may find a logo,
- I can search for one
- or we remove it (unless it is required for the nuget package to work)

**Comment by quicoli** [comment]
Hi

Are you sure it's violating? It's open source, see:
https://airbnb.design/introducing-lottie/

**Comment by Crayjin** [comment]
The Lottie software itself is open-source and licensed under Apache 2.0, but taking a screenshot from the website is something different (website has no license specified, so all rights are reserved by the owner unless provided differently).

**Comment by quicoli** [comment]
Ahh ok, no problem... Later I create an icon for our use

Thanks

**Comment by OmidID** [comment]
@Crayjin Can we have something like this:
image

You can see the Sharp(#) sign and Lottie together

**Comment by quicoli** [comment]
Wow! Perfect!

**Comment by Crayjin** [comment]
That looks very nice!

**Comment by OmidID** [comment]
Ok. I'll prepare it with better quality.

**Pull request merged**
